### ISSUE TITLE
got error dial tcp: lookup host.docker.internal: no such host

### ISSUE THREAD

**Issue by daleiyinsi** [openscrm/api-server#5]

**Comment by GargantuaX** [comment]
跟docker版本有关，如果无法访问，填写docker网络中宿主机的IP即可

**Comment by daleiyinsi** [comment]
> 跟docker版本有关，如果无法访问，填写docker网络中宿主机的IP即可

是models报错，models.Setup failed ，数据库不对

**Comment by GargantuaX** [comment]
填写docker-compose里面定义的服务名也可访问到指定容器服务
